// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm3RKlszizXyu17bBA7h0TPbBtkHtkQcI',
    appId: '1:824896860909:web:1393fcfd1fd73c330252e4',
    messagingSenderId: '824896860909',
    projectId: 'sunday-sport-club-a17cb',
    authDomain: 'sunday-sport-club-a17cb.firebaseapp.com',
    storageBucket: 'sunday-sport-club-a17cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-GzR5wbylVrcj7iREzCagJzrESo71Qs',
    appId: '1:824896860909:android:fb37e0dc9c8224c60252e4',
    messagingSenderId: '824896860909',
    projectId: 'sunday-sport-club-a17cb',
    storageBucket: 'sunday-sport-club-a17cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA881wLzz1npZaNIVOBdsydmbNcjvoQHQo',
    appId: '1:824896860909:ios:b9f7841610e2b9590252e4',
    messagingSenderId: '824896860909',
    projectId: 'sunday-sport-club-a17cb',
    storageBucket: 'sunday-sport-club-a17cb.firebasestorage.app',
    iosBundleId: 'com.example.flutterSsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA881wLzz1npZaNIVOBdsydmbNcjvoQHQo',
    appId: '1:824896860909:ios:b9f7841610e2b9590252e4',
    messagingSenderId: '824896860909',
    projectId: 'sunday-sport-club-a17cb',
    storageBucket: 'sunday-sport-club-a17cb.firebasestorage.app',
    iosBundleId: 'com.example.flutterSsc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm3RKlszizXyu17bBA7h0TPbBtkHtkQcI',
    appId: '1:824896860909:web:6ead2d594e80d8a50252e4',
    messagingSenderId: '824896860909',
    projectId: 'sunday-sport-club-a17cb',
    authDomain: 'sunday-sport-club-a17cb.firebaseapp.com',
    storageBucket: 'sunday-sport-club-a17cb.firebasestorage.app',
  );
}
